# .github/workflows/run-pipeline.yml
name: Update Stats Yearly

on:
  schedule:
    - cron: '10 18 5 11 *' # 5 de noviembre a las 18:10 UTC (19:10 Madrid)
  workflow_dispatch: # Permite lanzarlo manualmente tambi√©n

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Production # Define el entorno de despliegue
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm install

      - name: Debug env vars
        run: echo "Supabase URL $SUPABASE_URL"

      - name: Run pipeline
        run: npx tsx scripts/updateStats.ts

        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
